SharePoint:
  hostname: clearpeaks-portal1.sharepoint.com
  site_name: ''
  app_registration:
    tenant_id: 5dc9cc33-bce8-4581-bc49-05e82d3943c2
    client_id: d2927390-8649-484d-a75f-0703a34055ca
    client_secret: SP_CLIENT_SECRET
  innomap_doc:
    sp_link: https://saracus.sharepoint.com/:x:/r/sites/a_SYCP_InnovationCenter/Freigegebene%20Dokumente/General/SynvertInnoMapTracker.xlsx
